In [73]:
import pandas as pd

df = pd.read_csv("salaries.csv")
print(df.columns)

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [74]:
clean_df = df.dropna()
clean_df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business

In [75]:
# What college major has the highest mid-career salary? How much do graduates with this major earn?
highest_median = clean_df["Mid-Career Median Salary"].max()
row = clean_df["Mid-Career Median Salary"].idxmax()
major_highest_salary = clean_df["Undergraduate Major"].loc[row]
print(f'College major with highest mid-career salary is {major_highest_salary}.')
print(f'Graduates with this major earn {highest_median}.')

College major with highest mid-career salary is Chemical Engineering.
Graduates with this major earn 107000.0.

In [76]:
# Which college major has the lowest starting salary and how much do graduates earn after university?
lowest_s_median = clean_df["Starting Median Salary"].min()
row = clean_df["Starting Median Salary"].idxmin()
major_lowest_salary = clean_df["Undergraduate Major"].loc[row]
print(f'College major with lowest median starting salary is {major_lowest_salary}.')
print(f'Graduates with this major earn {lowest_s_median}.')

College major with lowest median starting salary is Spanish.
Graduates with this major earn 34000.0.

In [77]:
# Which college major has the lowest mid-career salary and how much can people expect to earn with this degree? 
lowest_m_salary = clean_df["Mid-Career Median Salary"].min()
row = clean_df["Mid-Career Median Salary"].idxmin()
major_m_lowest = clean_df["Undergraduate Major"].loc[row]
print(f'College major with lowest median mid-career salary is {major_m_lowest}.')
print(f'Graduates with this major earn {lowest_m_salary}.')

College major with lowest median mid-career salary is Education.
Graduates with this major earn 52000.0.

In [78]:
# Using the .sort_values() method, can you find the degrees with the highest potential? Find the top 5 degrees with the highest values in the 90th percentile. 

sorted_df = clean_df.sort_values(by="Mid-Career 90th Percentile Salary", ascending=False)
sorted_df["Undergraduate Major"].head()

17               Economics
22                 Finance
8     Chemical Engineering
37                    Math
44                 Physics
Name: Undergraduate Major, dtype: object

In [79]:
# Also, find the degrees with the greatest spread in salaries. Which majors have the largest difference between high and low earners after graduation.

spread_col = clean_df["Mid-Career Median Salary"] - clean_df["Starting Median Salary"]
clean_df.insert(1, "Spread", spread_col)
sort_df = clean_df.sort_values(by="Spread", ascending=False)
sort_df["Undergraduate Major"].head()

17               Economics
44                 Physics
37                    Math
8     Chemical Engineering
12    Computer Engineering
Name: Undergraduate Major, dtype: object

In [80]:
pd.options.display.float_format = '{:,.2f}'.format 
clean_df.groupby('Group').mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"30,450.00","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"25,781.82","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"36,950.00","53,862.50","90,812.50","56,025.00","157,625.00"